"""rename address

Revision ID: 471de62effc5
Revises: 93721a88e1cd
Create Date: 2025-06-20 11:44:44.612134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471de62effc5'
down_revision = '93721a88e1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###