"""rename department

Revision ID: 93721a88e1cd
Revises: bdf7d45275a7
Create Date: 2025-06-20 11:41:21.560885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93721a88e1cd'
down_revision = 'bdf7d45275a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###